trigger:

  branches:
   include:
     - main
     - feature/*
  paths:
     include:
       - $'(system.defaultworkingDirectory)/environment/dev'
variables:
  workdir: $'(system.defaultworkingDirectory)/environment/dev'
  
pool: new_agent

stages:
  - stage: build
    displayName: buildcode
    jobs:
      - job:
        displayName: terraforminit
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workdir)'
            backendAzureRmOverrideSubscriptionID: '8b0422c9-d3b4-4ad5-b676-1cd162a61f87'
            backendAzureRmResourceGroupName: 'Al_RG'
            backendAzureRmStorageAccountName: 'alstorage99'
            backendAzureRmContainerName: 'alcontainer'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            environmentAzureRmOverrideSubscriptionID: '8b0422c9-d3b4-4ad5-b676-1cd162a61f87'

  - stage: 
    displayName: scan
    jobs:
      - job: tfsac
        displayName: scanning tool
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: '''$(workdir)'''
      - job: checkov 
        displayName: scaningcheckov
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'cd ''''''$(workdir)'''''''
  
